remote_theme: chesterhow/tale

# Site settings
title: "Sasho Savkov"
description: "NLP Scientist and Engineer"
url: "http://sasho.io"
# Author
author:
  name: "Sasho"
  url: "https://sasho.io"
  email: "me@sasho.io"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

collections:
  code:
    output: true
  travel:
    output: true

